### ISSUE TITLE
How to use this for archiving?

### ISSUE THREAD

**Issue by To1ne** [akirak/org-reverse-datetree#1]
Great package, and I like to use it for archiving.

Now I have this in my `.org` file:

```
#+ARCHIVE: myfile-datetree.org::datetree/
```

And this properly makes a datetree when I archive items. But changing it to the following does not work:

```
#+ARCHIVE: myfile-datetree.org::reverse-datetree/
```

What is the proper syntax to do this?

**Comment by akirak** [comment]
Because archiving functions are provided by `org-archive.el` and it apparently does not support reverse date trees, you cannot do that. `org-archive.el` is part of Org mode, while `org-reverse-datetree` is not. To support a syntax like that, we have to contribute to Org mode.

It would be technically possible to implement an archiving function that creates a reverse datetree as part of this package. I personally don't find the feature very useful, because I don't care about how archived entries are ordered (so the built-in datetree archiving suffices). If someone implement the function, I am willing to merge it.

**Comment by To1ne** [comment]
I was just assuming it would be possible based on this from the README:

>This package provides functions for creating reverse date trees, which are similar to date trees created by built-in functions of Org mode (e.g. org-capture and org-archive) but in a reversed order.

TBH, it's not so important for me either. It would have been cool if it could.

**Comment by akirak** [comment]
I'm sorry for misleading. By that sentence, I meant date trees can be created by org-capture and org-archive, and this package provides some functions for creating reverse date trees. Instead of providing an archiving function, org-reverse-datetree provides a function for refiling.
