### ISSUE TITLE
FYI: ts.el

### ISSUE THREAD

**Issue by alphapapa** [akirak/org-reverse-datetree#5]
Hi Akira,

I don't remember if I've mentioned this to you before, but can't find mention of it in old issues, so FYI: you might find https://github.com/alphapapa/ts.el helpful for some of the timestamp-related code in this package.  I was looking at its code, and it looks like you do some things that ts.el is intended to help with.  e.g. I use it in this function in similar ways: https://github.com/alphapapa/unpackaged.el#refile-to-datetree-file-using-earliestlatest-timestamp-in-entry

Of course, I haven't published ts.el on MELPA yet, so you might not want to use it yet.

**Comment by akirak** [comment]
Hi,

I am aware of your ts.el package. For now, what I want the most is a function to parse a custom date format as supported by `format-time-string`. I need it for validating a datetree file (#3) as well as for merging two datetree files in different structures. It would be of great help if your package provided such a function. I looked for a date parsing package in MELPA, but there was none providing the exact feature. I will probably implement one on own, but it is of low priority.

I personally prefer getting a timestamp from particular properties rather than scanning the whole subtree, and as far as I handle org timestamps, the current implementation is sufficient. It is based on a corresponding function in the Org package. However, it would be better if it falls back to any timestamp text in the entire subtree when there is no property containing a timestamp.

**Comment by alphapapa** [comment]
> For now, what I want the most is a function to parse a custom date format as supported by `format-time-string`. I need it for validating a datetree file (#3) as well as for merging two datetree files in different structures. It would be of great help if your package provided such a function. I looked for a date parsing package in MELPA, but there was none providing the exact feature. I will probably implement one on own, but it is of low priority.

I'm not sure exactly what you mean, but it sounds like a feature that would fit in ts.el.  Feel free to open an issue there and I'll be happy to talk about implementing it.
